@startuml

entity User {
userId
----
----
username
hash
dirId
----
twitterId
facebookId
instagramId
}

entity File {
fileId
----
----
directoryId
ownerId
----
type
name
}

entity Directory {
directoryId
----
----
parentId
ownerId
----
name
}

User -o Directory
Directory --{ File
@enduml